### ISSUE TITLE
Functionality Breaks When an img Tag is not Wrapped in an Anchor Tag

### ISSUE THREAD

**Issue by davewhitley** [eikes/jquery.fullscreen.js#2]
I noticed that if you include an inline `img` tag anywhere in the HTML, then the functionality breaks. If you click on the gallery, the javascript does not run, and it just simply links to the raw .jpg. In order for the functionality to break, the `img` must not be wrapped in an anchor tag. For example:

Doesn't break functionality:

``` html
<a><img src="images/randomimage.jpg"/></a>
```

Breaks functionality:

``` html
<img src="images/randomimage.jpg"/>
```

The `img` tag can be located anywhere in the document, and it can be totally unrelated to the fullscreen gallery. This is problematic for blogs with lots of images, or if you have another image unrelated to the gallery somewhere on the page (a logo for example).

Any help would be appreciated.

**Comment by davewhitley** [comment]
Also, it seems that if you do include this HTML somewhere on the page, then a click on the image will just bring up a blank fullscreen slideshow:

``` html
 <a href="http://example.com"><img src="images/randomimage.jpg"/></a> 
```

Does this mean that we can't have images wrapped in anchor tags unless they are a part of the slidshow?

**Comment by eikes** [comment]
you'll just need to a give a class to your images which you'll use as a selector for the fullscreenslides call:

```
<a href="img1_l.jpg" rel="rel1"><img class="slides" src="img1_s.jpg"></a>
<a href="img2_l.jpg" rel="rel1"><img class="slides" src="img2_s.jpg"></a>

<img src="otherimage_noproblem.jpg">
```

and then:

```
$('.slides').fullscreenslides();
```
